javascript課題１−２
takahumi0806/javascript_sample pull request #2
Opened 2020-11-02 09:12 UTC by takahumi0806

【学習できる内容】
- While文の使い方
- prompt()の使い方
- alert()の使い方

ページを開いたら日本の首都はとアラートが出る
首都と記入したら正解とアラートが出る。
首都以外だと不正解とアラートが出る。
問題はループするようになっている。

2020-11-02 14:17 UTC, myzktkyk requested changes
何点か指摘をしております。

2020-11-02 14:17 UTC, myzktkyk commented on index.html
>      while (1) {
どちらかというと、以下の方が一般的です。
```suggestion
    while (true) {
```

2020-11-02 14:17 UTC, myzktkyk commented on index.html
>        var result = window.prompt("日本の首都は")
```suggestion
      const result = window.prompt("日本の首都は")
```
`var` は最近の javascript ではめったに使われないものになりました。
`let` または `const` を利用するようにして下さい。

2020-11-02 23:29 UTC, takahumi0806 commented on index.html
>      while (1) {
trueに修正しました

2020-11-02 23:29 UTC, takahumi0806 commented on index.html
>        var result = window.prompt("日本の首都は")
constに修正しました

2020-11-03 13:04 UTC, myzktkyk approved these changes
問題ありませんでした！
この Pull Request を Merge して、次の課題にお進みください！

2020-11-03 15:24 UTC, merged