javascript課題１−４
takahumi0806/javascript_sample pull request #4
Opened 2020-11-07 23:50 UTC by takahumi0806

【課題内容】
- 最初の段階でコンソールにタスク一覧が表示されている
- タスクには内容とジャンルがあり、各々表示される
- タスクを入力することができる
- ジャンルを入力することができる
- タスクとジャンルが入力されると追加され、表示される
【学習できる内容】
- 配列の使い方
- オブジェクトの使い方
- 関数の使い方

2020-11-09 00:37 UTC, niganium reviewed
お疲れ様です。課題の提出ありがとうございます。修正した後再提出をお願いいたします。

2020-11-09 00:37 UTC, niganium commented on index.html
> +    const items　= {掃除: '机を片付ける', 買い物: '牛乳を買う', 運動: '散歩をする'};
キーの値が「掃除」などは限定的すぎるのでジャンルと本文にて分類した方がいいと思います。
```
const task = {
    genre : 値
    content : "value"
};
```
のような構造を１タスク毎に作成し、それを配列に格納すれば個別にタスクを出力したりできるので便利です

2020-11-09 00:37 UTC, niganium commented on index.html
> +      console.log(i + ':' + '[内容]' + items[key] + '[ジャンル]' + key);
必須ではないですが、このような出力の場合はテンプレート文字列の方が便利です
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals

2020-11-09 00:37 UTC, niganium commented on index.html
> +      console.log(i + ':' + '[内容]' + items[key] + '[ジャンル]' + key);
また初回と2回目のコンソール出力はほぼ同じ内容なの関数にまとめられそうですね。
https://jsprimer.net/basic/function-declaration/

2020-11-09 10:35 UTC, takahumi0806 commented on index.html
> +    const items　= {掃除: '机を片付ける', 買い物: '牛乳を買う', 運動: '散歩をする'};
ハッシュを配列に格納できるように修正しました。

2020-11-09 10:36 UTC, takahumi0806 commented on index.html
> +      console.log(i + ':' + '[内容]' + items[key] + '[ジャンル]' + key);
テンプレート文字列にしました。
２回使用するところは関数にまとめました。

2020-11-09 14:04 UTC, myzktkyk requested changes
指摘点があります 🙏

2020-11-09 14:04 UTC, myzktkyk commented on index.html
> +    function item(items){
`item` という名前はちょっとどうかな…と思います。
関数やメソッド名は「これを使うと何が起こるか」が分かる名前が好ましいです。
具体的には「自動詞」「他動詞 + 目的語」を使うとよいです。

2020-11-10 00:38 UTC, takahumi0806 commented on index.html
> +    function item(items){
修正しました

2020-11-10 13:08 UTC, myzktkyk approved these changes
指摘事項が修正されていることを確認しました！

2020-11-10 13:20 UTC, merged